language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
  - secure: Chr8/5N6cHoYRqQh2TI/JgVnEg6ARgXFgeUXfXYYrus+nexFKJt3P0cqX4/QkMUvg2zxPkpU3I3Kr3DjPKmUEFjWWq8AE653hLxDeHf7ayHjQJ1SXmLGdkWPPsdT/L/leX3x244soW57EPVNtPEJGY47Ff/CmKZETDw34f7tgDfEemVEgdBnjW3s+orurxiCy5hJLk2amU2REVdY1KuXw9OGoVQO6Mjm9BE+UeF2giLrLuBwiC6VjN71XgLeavb9L/0awN3IbmFFPdBvU5ZVdUaUadoJ1IqdDsczaDbaytXv7WGbHJtmJNXDBX44hLuVhp+yIkvlaW1LDEEBAEVNHyGLjtzpllApNMs8dEAWgSulKSb9JfduYKcGJLjXNxRuPwgbAmObeHdoe1EXeksOcojOw0o46ASqDFwbrWpCtcBDgFdEJuXSB2k5btAwgRvmbzq80L0WmcxkV2L9kDzKGG+qbrTGoN+mXCtbkUb7Lhxkk4U5jkP/Wq1nm+zOcjMo5SNTVIZn304BmujV02m821onXTpbnPQgrGJmsv1tLff8VA5D5xM0Cv4Ax7vLdH983oyth/E/lvH0/nCTTsI9EeVC84mFwaHZlTaGWshj2Fz1z2UZO27yx4RwS3ZhgYqLaCCD1v61Cs9F7QClmiwkWxlLH/OP+RQKWWnz8w1dSnI=
  - secure: meU9vbjgpHp9iZxwYVENOdh3qd4vyz7xKnFt7C1MAtj8gyQ8B5aRiWd2qxt0HwsV/379uQ7Bn2wzLHyVlmMqNcBXJRh5NtrSC4anAatPzIJwS1elel342f84tJC2xrLWdasptEpJB0fJn6LWR9qUkFnGDw1FI/ZBVi/wMlYZAVlodf6jJlEQnDKI2T7WHPq/Pl7un31H41CLufej08LxTkNWI3ycFOHa0BBp/FrGulF2ScEL6wlU/ufNA4Yw6Ois7tx1K2S+1qtuQTlxe6wER8fTdbSuJfv/lQmTuhHJRSBK/VGy0c8kYVXdN8+IVxSVotFDd8EpRDUUt0Yf/+h7/aVB3Oc3pt032FnQodwzt0H5l/zgyaMsJPKB757Ulyo/iNGq5IDgY6zaVA1ic6+GHDXvopxi4Dw5TAWJr3Lx/Z5MS6EcJhjWKMySDLlketb/RPKoRNZ09eh/+kMfw/ItLEEk0wc2KHx0unKk0vYSZy2jZGtLI2mEoUKs8zUNnDHqx4eqQTJQXUF9UcYxmdvj9K9LKwgLW64ooVSpTbh1u74SJ7PUB2eZic3mK4/mEvJHFDFAe0Tza8N67VJs+oqAgzsSK46N+q9uyBNa5NLRywdtepDqitwY8rpe2HZ3sJzB1T+yeotPv+7bKkfK2XNApGK/xN73OM/0tLTGlXIJW/E=
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: wKSzyAjdRQcHx90BIiMgNV2ty1p16x54jzBLBPuIxYJ6UTeGhDFs2f+qdkD6WkCeyeVJ9o/iV9In9cP4EhiwlLc5RHTrRr4e9WzZOJBqHiA/FfFV9MMZ5DCRPaVAlGrs9V3EtREJUM4bQwkbydNzzbhE1U8MGY5iUpd+fAsBvmVIyGA4uv+meLdMKX+q7Jlilo+BX5HzAldWH0oFQ0x4OvLLvheD1+NCp8Y2Jv7dl4A4KvFQIp6dsgs42v1D35As3d2eg+ZztoTWS+3Yzgmj7WdyoT0QGiG/0AUtK8ueewIw9HUIe8hdTRC1UaIBG1NbwdgzQvEH72aWp4Hvtz4JwgdhNSKz2CYKDWT38SBTJ6KoDZE08+T3Fk1FhuT0NYxaXmCRrUod0Ec/hRqw/svCIGgl+CiCWYupspeyk/qm/BupRlsFnmxBBRcLk3irlyWkzc/vUSTqIcX7ltXuwSw2bcNzIJrKD3uJnax46BRips2M7ptzks2vUneoW3Kj7Bfs+qwwNavbD9ChBp+d4KwS5E52grAMofkVKvSROFigM73v0fg6lD9uhKlMBlMUDDOuU406pXkrllkhz33KCBXjfrB/N1EdAApTrXp5TIAMsZ/sRQRcMNdwTiHer9hz0HptFjSpc3Gor3KEW55w27SU5w6d4ARAKpC9vty2w08UMF0=
  on:
    repo: FreeAllMedia/proven
    branch: master
